config/routes.rb
Rails.application.routes.draw do
  root 'people#index'
  resources :people, path: 'pessoas', path_names: { new: 'criar', edit: 'editar' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  has_many :potatoes, dependent: :destroy

  accepts_nested_attributes_for(
    :potatoes,
    reject_if: lambda { |attrbs| attrbs['content'].blank? },
    allow_destroy: true
  )
  # Lambda: basicamente uma função anônima em ruby.
end

app/models/potato.rb
class Potato < ApplicationRecord
  belongs_to :person
  validates_presence_of :content
  validates :content, length: { in: 20..50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
    3.times { @person.potatoes.build } # Inicializa algumas batatas para o formulário.
  end

  # GET /people/1/edit
  def edit
    new_potatoes = 3 - @person.potatoes.count
    new_potatoes.times { @person.potatoes.build }
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(
        :name, :age, :student, :birth, potatoes_attributes: [:id, :content, :happy, :_destroy]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/potatoes_helper.rb
module PotatoesHelper
  def potato_happy_text(potato)
    if potato.happy
      'Batata feliz!'
    else
      'Batata triste :('
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExemploModels</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2>Alguns erros impediram esta pessoa de ser salva:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :student %>
    <%= form.check_box :student %>
  </div>

  <div class="field">
    <%= form.label :birth %>
    <%= form.date_select :birth %>
  </div>

  <ul>
    <%= form.fields_for :potatoes do |potato_form| %>
      <li>
        <div class="field">
          <%= potato_form.label :content %>
          <%= potato_form.text_field :content %>
        </div>

        <div class="field">
          <%= potato_form.label :happy %>
          <%= potato_form.check_box :happy %>
        </div>

        <div class="field">
          <%= potato_form.label :_destroy, "Excluir?" %>
          <%= potato_form.check_box :_destroy %>
        </div>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editando Pessoa</h1>

<%= render 'form', person: @person %>

<%= link_to 'Exibir', @person %> |
<%= link_to 'Voltar', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pessoas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Estudante</th>
      <th>Nascimento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.age %></td>
        <td><%= t person.student %></td>
        <td><%= l person.birth %></td>
        <td><%= link_to 'Exibir', person %></td>
        <td><%= link_to 'Editar', edit_person_path(person) %></td>
        <td><%= link_to 'Excluir', person, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Pessoa', new_person_path %>

app/views/people/new.html.erb
<h1>Nova Pessoa</h1>

<%= render 'form', person: @person %>

<%= link_to 'voltar', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @person.age %>
</p>

<p>
  <strong>Estudante:</strong>
  <%= t @person.student %>
</p>

<p>
  <strong>Nascimento:</strong>
  <%= l @person.birth %>
</p>

<ul>
  <% @person.potatoes.each do |potato| %>
    <li>
      <p><%= potato.content %></p>
      <p><%= potato_happy_text(potato) %></p>
    </li>
  <% end %>
</ul>

<%= link_to 'Editar', edit_person_path(@person) %> |
<%= link_to 'Voltar', people_path %>